env:
  global:
  - secure: "yr+6iVZQ/N0fz3ZYgq29VP2ifLGQSSK1GiTlThVEMf5lI5vqHSnXf78cMaiCj94H2XbZF5JQjPkrkiXD0b+67dAcP4bI1LjtDUhXETfhgS+xvYnhzhuN9jOwU4OmyWDwtaU8vo3bmvbLYBQdxQ2REp84k+fcCIPyrV/Hlj2Ptt3aoiMBzyfPRa7vtXRryeOd5a5HxMnQJRgGxOX9VvRVb9suR/qALAfyBxQxikpKUw2nmS0+IeXMGMueqLfzjImwgdXJ3DFQGB9Y67AQTLmPoGR8dPDHPX8KM+bq6dqJmBRIxMeJjdS8OBVJGK6/OU4cCCcRTjrtlxfcFW9EFAnc8ZPm4FLZN+1Wk+ExllrBqDz7MBmFgwQG5ssv8YxYtXJgVOHh3YbToRcGqHn9CVCj72mun68B/qBwts0bzaS4TPDOtJTbCODRywVx02KLp0HciZtZZF+Mj6yjhlcI0Qfm5lYn2LxQ5wfFG6EdwpUhaNJprlzyZNeGn2yAp3EFHSe6K/7HygJZeWWe3kvvCTwgds7k1QxrqTzYEpLa/vRxxMimE4uBoCAHmwdAWJjflbCv0+OFWrx5QjqT5Vx8nJEFxrE9BfGNgZ92uCdB1X6bqEhpSFgHRujJ49HWZLXITfaqRK9fDEoSnbbjiECxyoSDjRHT9iqfC8ldsDQzq02/5c0="
  - secure: "eR6Oy0kZPnE+TbciFx78kTQeXHMzu48PCgU7SnPnUtqBhUjWcLVD4GnCA5zrQvPGXBEYMUg7MELRvBmCHfdG5hT7dnNMbP4x3qgwGI2JTi3Ty/4PkwnBwa389Oeid3ecW2sgefzqgSagkPlht6zo3Em9g8STGDyvYmr165stvry91BfVPC/fv1YsSmmlnN51gWDiq61m+oHplVYmG5eFfxmLDD56F/eNWe9mOiCRkVP6cS6BlAVCqA7J1Y65PnFIJUdnG8oNumqXAfTAtmIQDF37MxN0ZA/LmlGytbNQlr208O8UWW7jUJRxR7oPQmxHVZ3fdldP08siFLdvZ9zIIXMpK9LZRm/qMv7+L8FjbOH1rjkmaGl+OBpzugQOVfsl+khjJCJ2XDOG376H2vti4uvabdROIZsGI8gRXoJHZGCic6XqCaqSTLHgPM/AfsVir1YOXmMENcZF1Pg3GrYOxD750bV76cK+wSPTgaDq/MN088EjQxw7MNlE+cZkqo1CgbaJcfLjnq5RiQYj98FBa2d51U/FAXHH/NChs30QTyXhRVZ3lclXqzX8w8ChIvk/jxRj38txIMBymAT2WXGLhfccp06oegBui+UdjqOUaztHQjs1py4kL/wazlze0CP9oh1eV9coZqbC6HTOGBMQTibNoNJ+DX9KZIPu7sx8Tmo="
# jfrog(travis)
  - secure: "Xc3/wbLqdzYgnotyBHzvXLf/v2oUQDkNoD9ot2r7+lQH2WZyukpEltlydlrwPd1+sLbd4wSOTxgpIDYzXUUDnPMxP7aGKdtdds9AZ3dFYctdWLC6yvIT8Yz73eRtILDZdQuhJMkHrziF/tWRCRkikyM65sXxhHxXKMd0EQ6SyyeHj0GWz7+sFlzca6FmkZGsioTW7cFeVW5nlAxPRQQqUeoLbe/iRHGhephOd0CeOdeP5c2OtSt6eD43YRsIFAFQi8F5+BY1pHGWMvLSy8zZGWX1NuAwXOue7eZEewQRF4WOUjREdwrPXhMfruUmPhvG4HPEU8/ofmf/XcfJMrQ+VNzKvBtj/JsQBlfvTGuqHOMVhj8CRYZgqjjHKmGyEiUjwEeVEa8+tEG0SiJtsLTTlOYf1gJmkjX6uj6aldF00RvqDchaPkDiGoq6ooa6vlWboOuTZU9a6hACfk1ZxHFQR2OBUiBqr3UC0tbOKC+DRiRT6+KyQb9I75bFNDpYV7iy8HKkOkuYmfTia+yYekM7IukRRq8J1JY6FnxC1TbIS4Yw01WPqzP/ln51SSM5p48oz2T3ETX6kIQK/u67wtMbc6iBhSY2//wzz/DTUU52+Uaw8sS8Y7b3WshLPcJ2ibfxSlsuAcLpKRM1cFqH3kIm5YGbq0bpP1/c/KbTf9Fveqs="

language: java
jdk:
- openjdk8

script:
- mvn -Prelease -f parent/pom.xml verify

after_success:
- echo "TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}"
# Skip deployment on Pull Request
- if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then exit 0; fi
# Skip deployment if branch is not master
- echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"
- if [ "${TRAVIS_BRANCH}" != "master" ]; then exit 0; fi

# Deployment steps
- set -e
# extract persion from repo pom
- VERSION=$(basename com.cthing.cmakeed.site/target/CMakeEd-*.zip| sed -r -n 's/.+-([0-9]+(\.[0-9]+)*).zip$/\1/p')
# upload p2 repo zip to bintray as a new version
#- curl -f -T com.cthing.cmakeed.site/target/CMakeEd*${VERSION}.zip -u${BINTRAY_USER}:${BINTRAY_API_KEY} https://api.bintray.com/content/${BINTRAY_USER}/p2-zip/cmakeed/${VERSION}/
- curl -H ${KEY} -T com.cthing.cmakeed.site/target/CMakeEd*${VERSION}.zip -X PUT https://fifteenknots.jfrog.io/artifactory/p2-zip/cmakeed/
